language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
    - composer selfupdate
    - composer install --dev --prefer-source

script:
    - phpunit --colors --coverage-text

notifications:
  email:
    on_success: never
    on_failure: always
